version: "3.9"
services:
    school-management:
        container_name: school-management
        image: loqo71la/school-management
        environment:
            SM_API_URL: http://localhost:8080/api
        ports:
            - 5173:80