name: Production Deployment

on:
  push:
    branches:
      - main

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  web-client-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-client
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Generate .env file
        env:
          SM_API_URL: ${{ secrets.REACT_APP_SM_API_URL }}
          API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          APP_ID: ${{ secrets.REACT_APP_APP_ID }}
          MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}
        run: |
          touch .env.production
          echo REACT_APP_SM_API_URL="$SM_API_URL" >> .env.production
          echo REACT_APP_API_KEY="$API_KEY" >> .env.production
          echo REACT_APP_AUTH_DOMAIN="$AUTH_DOMAIN" >> .env.production
          echo REACT_APP_PROJECT_ID="$PROJECT_ID" >> .env.production
          echo REACT_APP_STORAGE_BUCKET="$STORAGE_BUCKET" >> .env.production
          echo REACT_APP_MESSAGING_SENDER_ID="$MESSAGING_SENDER_ID" >> .env.production
          echo REACT_APP_APP_ID="$APP_ID" >> .env.production
          echo REACT_APP_MEASUREMENT_ID="$MEASUREMENT_ID" >> .env.production
        shell: bash

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCHOOL_MANAGEMENT_LOQO71LA }}'
          channelId: live
          projectId: school-management-loqo71la

  rest-api-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rest-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Database connection
        run: |
          sed -i -E "s/url=.+/url=${{ secrets.DB_URL }}/" ./src/main/resources/application.properties
          sed -i -E "s/username=.+/username=${{ secrets.DB_USERNAME }}/" ./src/main/resources/application.properties
          sed -i -E "s/password=.+/password=${{ secrets.DB_PASSWORD }}/" ./src/main/resources/application.properties

      - name: Docker login
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login -u _ --password-stdin registry.heroku.com

      - name: Build Docker image
        run: heroku container:push web -a school-management-loqo71la

      - name: Deploy to Heroku
        run: heroku container:release web -a school-management-loqo71la
